apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: rnk-expense
  labels:
    app: mysql
    tier: database
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
      project: expense
  template:
    metadata: 
      labels:
        app: mysql
        tier: database
        project: expense
    spec:
      containers:
        - name: mysql
          image: naveenrajoli/mysql:1.0
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: rnk-expense
spec: 
  selector: # labels are used as selectors
    app: mysql
    tier: database
    project: expense
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306



    
 