apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: rnk-expense
  lables:
    app: mysql
    tier: database
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
      project: expense
  template:
    metadata: 
      labels:
        app: mysql
        tier: database
        project: expense
    spec:
      containers:
        - name: mysql
          image: naveenrajoli/mysql:1.0


    
